USE hotel;
INSERT INTO room_type VALUES ('standard', 20);
INSERT INTO room_type VALUES ('business', 500);
INSERT INTO room_type VALUES ('president', 10000);
INSERT INTO room_status VALUES ('available');
INSERT INTO room_status VALUES ('unavailable');
INSERT INTO room VALUES ('101', 'standard', 'available');
INSERT INTO room VALUES ('102', 'standard', 'available');
INSERT INTO room VALUES ('103', 'standard', 'available');
INSERT INTO room VALUES ('201', 'standard', 'available');
INSERT INTO room VALUES ('202', 'standard', 'available');
INSERT INTO room VALUES ('203', 'standard', 'available');
INSERT INTO room VALUES ('301', 'standard', 'available');
INSERT INTO room VALUES ('302', 'standard', 'available');
INSERT INTO room VALUES ('303', 'standard', 'available');
INSERT INTO room VALUES ('401', 'business', 'available');
INSERT INTO room VALUES ('402', 'business', 'available');
INSERT INTO room VALUES ('501', 'business', 'available');
INSERT INTO room VALUES ('502', 'business', 'available');
INSERT INTO room VALUES ('601', 'president', 'available');
INSERT INTO room VALUES ('701', 'president', 'available');
INSERT INTO supply VALUES ('wt1', 'water', 1);
INSERT INTO supply VALUES ('bm1', 'banh mi', 2);
INSERT INTO supply VALUES ('cc1', 'coca cola', 2);
INSERT INTO supply VALUES ('hh1', 'hao hao', 3);